name=VEGA_RV3028
version=1.0.2
author=Kaustav Saloi (C-DAC)
maintainer=Kaustav Saloi <kaustavsalois@gmailcom>
sentence=RV-3028 RTC library for VEGA Thejas32 (C-DAC) boards with multi-I2C support
paragraph=Custom lightweight library for RV-3028-C7 RTC used in VEGA Thejas32 platform with proper I2C handling, EEPROM readiness check, and burst read support.
category=Device Control
url=https://github.com/kaustavsaloi/VEGA_RV3028
architectures=*